<?php

/**
 * @file
 * Contains ham_station.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ham_station_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ham_station module.
    case 'help.page.ham_station':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Information about amateur radio stations') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function ham_station_cron() {
  $config = \Drupal::configFactory()->get('ham_station.settings');

  if (!$config->get('geocode_cron_enable')) {
    return;
  }

  /** @var \Drupal\ham_station\Geocoder $geocoder */
  $geocoder = \Drupal::service('ham_station.geocoder');

  $geocoder->geoCode();
  $geocoder->copyGeocodeForDuplicates();
}

/**
 * Implements hook_theme().
 */
function ham_station_theme($existing, $type, $theme, $path) {
  return [
    'ham_station' => [
      'render element' => 'elements',
    ],
    'ham_neighbors' => [
      'variables' => [
        'form' => NULL,
        'view' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess() for ham_station.
 */
function template_preprocess_ham_station(&$variables) {
  /** @var \Drupal\ham_station\Entity\HamStation $entity */
  $entity = $variables['elements']['#ham_station'];

  $variables['callsign'] = $entity->callsign->value;

  if (empty($entity->organization->value)) {
    $variables['name'] = sprintf('%s %s %s',
      $entity->first_name->value, $entity->middle_name->value, $entity->last_name->value
    );
  } else {
    $variables['name'] = $entity->organization->value;
  }

  $variables['address'] = $variables['elements']['address'];
  $variables['attributes']['data-lat'] = $entity->field_location->lat;
  $variables['attributes']['data-lng'] = $entity->field_location->lng;
}
